apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger-agent
        image: jaegertracing/jall-in-one
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
      volumes: []

