apiVersion: apps/v1
kind: Deployment
metadata:
  name: minke
  labels:
    app: minke
spec:
  selector:
    matchLabels:
      app: minke
  replicas: 2
  template:
    metadata:
      labels:
        app: minke
    spec:
      containers:
      - name: minke
        image: "minke:latest"
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        ports:
          - name: https
            containerPort: 443
            protocol: TCP
        ports:
          - name: http3
            containerPort: 443
            protocol: UDP
        volumeMounts: []
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger.default:14267"
      volumes: []
