[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0-pre1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.0-beta.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.0-beta.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.0-beta.2"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "master"
  name = "golang.org/x/text"

