apiVersion: v1
kind: Service
metadata:
  labels:
    component: ingress-controller
  name: minke
  namespace: default
spec:
  selector:
    app: minke
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http3
    port: 443
    protocol: UDP
    targetPort: 443
  - name: admin
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
