apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: default
spec:
  selector:
    app: jaeger
  ports:
  - name: web
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: tchan
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: thrift
    port: 14268
    protocol: TCP
    targetPort: 14268
  type: ClusterIP
